## Numpy

### 1. Numpy Array and Operation

- numpy의 기본적인 사용법에 대해서 배워봅니다.


- numpy에서 numpy.array를 만드는 여러가지 방법과 지원하는 연산자에 대해서 공부합니다.

### 1.1. Numpy Array creation

In [4]:
# numpy 라이브러리를 불러옵니다.
import numpy as np

In [1]:
# 파이썬 리스트 선언
data = [1,2,3,4,5]
data

[1, 2, 3, 4, 5]

In [15]:
# 파이썬 2차원 리스트(행렬) 선언
data2 = [[1,2],[3,4],[5,6]]
data2

[[1, 2], [3, 4], [5, 6]]

In [5]:
# 파이썬 list를 numpy array로 변환합니다.
arr = np.array(data)
# numpy array를 만드는 방식의 대부분은 파이썬 리스트를 np.array로 변환하는 방식입니다.
arr

array([1, 2, 3, 4, 5])

In [16]:
# 2차원 리스트를 np.array로 만듭니다.
arr2 = np.array(data2) # data2라는 리스트를 numpy array로 만들어라.
arr2 # 2차원 numpy -> 행렬

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
# 0부터 9까지 숫자를 자동으로 생성한 array
np.array(list(range(10)))
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# 10부터 99까지 숫자를 자동으로 생성한 array
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [18]:
arr.shape #(5, ) != (5, 1)
arr2.shape #(3,2)

(3, 2)

### 1.2. Reshaping array

In [19]:
# 3 x 3 행렬을 만들어봅시다.
x = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
# reshape을 이용하여 만들어봅시다.
np.arange(1,10).reshape(3,3) # (9,) -> (3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
# row vector를 column vector로
np.arange(6).reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [26]:
# 펼치기
x.reshape(-1, ) # -1이 나오면 다른 숫자에 맞춰서 shape 바뀐다.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 1.3. Concatenation of arrays

In [36]:
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6]])
# arr1 + arr2 = ?
print(arr1 + arr2)
L = [1,2,3]
L2 = [1,2,3]
print(L+L2)
# arr1와 arr2를 합칩니다
np.concatenate([arr1,arr2], axis=0)

[[5 7 9]]
[1, 2, 3, 1, 2, 3]


array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
# stacking vertically
np.vstack([arr1,arr2])

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
# stacking horizontally
np.hstack([arr1,arr2])

array([[1, 2, 3, 4, 5, 6]])

## 1.4. Array Arithmetic (like vector) --> Universal Function

In [40]:
# v1 = (1, 2, 3), v2 = (4, 5, 6) 벡터 2개 생성하기.
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [39]:
# 리스트로 더하기 연산해보기
L = [1,2,3]
L2 = [4,5,6]
L+L2

[1, 2, 3, 4, 5, 6]

In [41]:
#  vector addition
v1 + v2

array([5, 7, 9])

In [42]:
#  vector subtraction
v1 - v2

array([-3, -3, -3])

In [43]:
# (not vector operation) elementwise multiplication
v1 * v2

array([ 4, 10, 18])

In [44]:
# (not vector operation) elementwise division
v1/ v2

array([0.25, 0.4 , 0.5 ])

In [45]:
# dot product
v1 @ v2 # 1x4 + 2x5 + 3x6

32

### 1.5. Broadcast and Universal Function

- 서로 크기가 다른 numpy array를 연산할 때, 자동으로 연산을 전파(broadcast)해주는 기능. 행렬곱 연산을 할 때 편리하다.

In [65]:
arr1 = np.array([1,2,3])

In [48]:
arr2 = np.array([[-1,-1,-1],
                 [1,1,1]])
arr2.shape 

(2, 3)

In [49]:
# 2개의 array를 더해보면?
arr1 + arr2 # 2->2->3(v)

array([[0, 1, 2],
       [2, 3, 4]])

In [50]:
# 2개의 array를 곱해보면? (**)
arr1 * arr2

array([[-1, -2, -3],
       [ 1,  2,  3]])

- Universal Function : broadcast 기능을 확장해서, numpy array의 모든 원소에 동일한 함수를 반복문으로 적용한 것과 같은 효과를 내는 기능.

In [68]:
# lambda : 한줄로 쓰는 함수식
# lambda 매개변수 : 표현식
# f = lambda x : 1/x

f= lambda x : 1/x

arr1 = np.array([1.,2.,3.])

for i in range(arr1.shape[0]):
    arr1[i] = f(arr1[i])
print(arr1)

arr1 = np.array([1.,2.,3.])
print(1 / arr1) # universal func

# print( (lambda x : 1/x)(5) )
# print( map(lambda x : 1/x, range(1,5)) )
# print( list(map(lambda x : 1/x, range(1,5))) )

[1.         0.5        0.33333333]
[1.         0.5        0.33333333]


In [69]:
# f = lambda x : x + 2
arr1 = arr1 +2
arr1

array([3., 4., 5.])

### 1.6. Indexing

- numpy array의 인덱싱은 python list의 인덱싱과 같다.

In [72]:
arr1 = np.arange(10)

In [73]:
# 첫번째 원소
arr1[0]

0

In [74]:
# 마지막 원소
arr1[-1]

9

In [77]:
# 앞에서부터 원소 3개 slicing
arr1[:3]

array([0, 1, 2])

In [79]:
arr2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
arr2.shape

(3, 4)

In [82]:
# arr2의 2row, 3column 원소 = 7
arr2[1][2]
arr2[1, 2] # numpy array indexing에서 추가된 것

7

In [91]:
# arr2의 세번째 column [3, 7, 11]
arr2[0,2]
arr2[1,2]
arr2[2,2]

arr2[0:3,2]
arr2[:, 2]

array([ 3,  7, 11])

In [90]:
# arr2의 두번째 row
arr2[1, :]

array([5, 6, 7, 8])

## 2. Numpy Methods

- numpy에서 사용되는 여러가지 함수들을 사용해봅시다.

### 2.1. Math Functions 

In [92]:
# 표준정규분포에서 random sampling을 한 원소를 가지는 5x3 행렬을 만든다.
mat1 = np.random.randn(5, 3)
mat1

array([[ 1.19763745, -0.4674038 ,  0.42303687],
       [-0.31638076, -0.06639783,  0.805422  ],
       [-0.59721212,  0.70132368, -0.96758865],
       [-2.59381648,  0.18575846, -1.91802523],
       [ 2.43868404,  0.71053949,  0.35792387]])

In [93]:
# mat1에 절대값 씌우기
np.abs(mat1)

array([[1.19763745, 0.4674038 , 0.42303687],
       [0.31638076, 0.06639783, 0.805422  ],
       [0.59721212, 0.70132368, 0.96758865],
       [2.59381648, 0.18575846, 1.91802523],
       [2.43868404, 0.71053949, 0.35792387]])

In [94]:
# mat1 제곱하기
np.square(mat1)

array([[1.43433546e+00, 2.18466312e-01, 1.78960189e-01],
       [1.00096782e-01, 4.40867229e-03, 6.48704606e-01],
       [3.56662317e-01, 4.91854900e-01, 9.36227798e-01],
       [6.72788395e+00, 3.45062061e-02, 3.67882079e+00],
       [5.94717987e+00, 5.04866374e-01, 1.28109497e-01]])

In [95]:
# mat1의 제곱근 구하기 : 루트
np.sqrt(mat1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


array([[1.09436623,        nan, 0.65041284],
       [       nan,        nan, 0.89745307],
       [       nan, 0.8374507 ,        nan],
       [       nan, 0.43099706,        nan],
       [1.56162865, 0.84293505, 0.59826739]])

In [98]:
# linear algebra functions
vec = np.array([1,2,2])

# 1. norm
np.linalg.norm(vec) # vector L2 norm 루트(1^2 + 2^2 + 2^2) 

# 2. eigenvalue
mat = np.array([[1,2],
                [3,4]])
np.linalg.eig(mat)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

### 2.2. Aggregation functions 

In [99]:
mat2 = np.random.rand(3, 2)
mat2

array([[0.50613784, 0.32135396],
       [0.67831896, 0.23950535],
       [0.22285105, 0.91112084]])

In [102]:
# Summation
np.sum(mat2)
np.sum(mat2, axis=1)
np.sum(mat2, axis=0)

array([1.40730785, 1.47198015])

In [108]:
# mean
np.mean(mat2, axis=1)
np.mean(mat2, axis=0)

array([0.46910262, 0.49066005])

In [106]:
# std 표준편차
np.std(mat2)

0.25000350548901995

In [107]:
# min, max
np.min(mat2, axis =0)
np.max(mat2, axis =1)

array([0.50613784, 0.67831896, 0.91112084])

In [111]:
# 최소값이 있는 Index
np.argmin(mat2, axis=0)
np.argmin(mat2, axis=1)

array([1, 1, 0])

In [112]:
# 최대값이 있는 Index
np.argmax(mat2, axis=1)

array([0, 0, 1])

In [113]:
mat2

array([[0.50613784, 0.32135396],
       [0.67831896, 0.23950535],
       [0.22285105, 0.91112084]])

In [118]:
# 그냥 정렬 (오름차순 정렬만 지원합니다)
np.sort(mat2, axis=0)

# 만약 내림차순 정렬을 하고싶다면
# np.sort(mat2, axis=0)[::-1]

array([[0.22285105, 0.23950535],
       [0.50613784, 0.32135396],
       [0.67831896, 0.91112084]])

In [117]:
# index를 정렬
np.argsort(mat2, axis=0)

array([[2, 1],
       [0, 0],
       [1, 2]])

## 3. Performance Check

- Universal Function 기능을 통해 반복문을 사용한 것보다 훨씬 빠른 성능을 냅니다.


- 직접 실험을 통해 그 차이를 확인해보겠습니다.

In [119]:
np.random.seed(0)

def reverse_num(values):
    output = np.empty(len(values))
    
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    
    return output

In [120]:
# 1부터 100까지 범위에서 1000000개를 랜덤으로 뽑아서 array를 만듭니다.
big_array = np.random.randint(1, 100, 1000000)
big_array

array([45, 48, 65, ..., 93, 62, 19])

In [121]:
%timeit reverse_num(big_array)

1 loop, best of 5: 2.28 s per loop


In [122]:
%timeit 1.0 / big_array

100 loops, best of 5: 2.54 ms per loop
