In [1]:
pwd

'/Users/aiden/Dropbox/Mac/Desktop/ch9_추천시스템'

In [2]:
import pandas as pd  # 데이터 분석을 위한 라이브러리
import numpy as np   # 넘파이 : 숫자 계산

# 워닝(버전, 업데이트 문제, 에러는 아님) 코드는 실행되는데 정보. 귀찮을 때 워닝 끄기
import warnings
warnings.filterwarnings('ignore')

In [9]:
movies_df = pd.read_csv('tmdb_5000_movies.csv')

In [10]:
print(movies_df.shape)  # 행, 열 개수 파악
movies_df.head()

(4803, 20)


budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [11]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4803 non-null   int64  
 1   genres                4803 non-null   object 
 2   homepage              1712 non-null   object 
 3   id                    4803 non-null   int64  
 4   keywords              4803 non-null   object 
 5   original_language     4803 non-null   object 
 6   original_title        4803 non-null   object 
 7   overview              4800 non-null   object 
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object 
 10  production_countries  4803 non-null   object 
 11  release_date          4802 non-null   object 
 12  revenue               4803 non-null   int64  
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object 
 15  status               

In [12]:
# 필요한 컬럼만 추출
movies_df = movies[['id','title','genres','vote_average','vote_count','popularity','keywords','overview']]
movies_df.head(3)

id                                     title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   

                                              genres  vote_average  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.3   

   vote_count  popularity                                           keywords  \
0       11800  150.437577  [{"id": 1463, "name": "culture clash"}, {"id":...   
1        4500  139.082615  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2        4466  107.376788  [{"id": 470, "name": "spy"}, {"id": 818, "name...   

                                            overview  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...

In [24]:
print(type(movies_df['genres'][0]))
movies_df['genres'][0]

<class 'str'>


'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [23]:
from ast import literal_eval

print(type(literal_eval(movies_df['genres'][0])))
literal_eval(movies_df['genres'][0])

<class 'list'>


[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [18]:
type(movies_df['genres'][0])
# str 타입인 것을 확인할 수 있다.

str

### genres, keywords 칼럼들의 str형태를 list형태로 바꿔주기

In [25]:
movies_df['genres']

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...                        
4798    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4799    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4800    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4801                                                   []
4802                  [{"id": 99, "name": "Documentary"}]
Name: genres, Length: 4803, dtype: object

In [26]:
from ast import literal_eval  # 문자열 파싱 라이브러리
movies_df['genres'] = movies_df['genres'].apply(literal_eval)
movies_df['keywords'] = movies_df['keywords'].apply(literal_eval)

In [30]:
movies_df['genres'][0][0]['name']

'Action'

In [31]:
type(movies_df['genres'][0])
# str타입에서 list타입으로 바뀐 것을 확인할 수 있다.

list

### list 내 여러개 딕셔너리의 name키에 해당하는 값들을 리스트로 변환

In [94]:
movies_df['genres']

0       [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
1       [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2       [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
3       [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
4       [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
                              ...                        
4798    [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
4799    [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
4800    [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4801                                                   []
4802                  [{'id': 99, 'name': 'Documentary'}]
Name: genres, Length: 4803, dtype: object

In [95]:
movies_df['genres'][0]

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [32]:
movies_df['genres'] = movies_df['genres'].apply(lambda x : [ y['name'] for y in x])
movies_df['keywords'] = movies_df['keywords'].apply(lambda x : [ y['name'] for y in x])

In [33]:
movies_df[['genres']][0:3]

genres
0  [Action, Adventure, Fantasy, Science Fiction]
1                   [Adventure, Fantasy, Action]
2                     [Action, Adventure, Crime]

In [34]:
movies_df[movies['genres']=='[]']

id                                              title genres  \
3971  191229                                             Iguana     []   
3992  346081                                          Sardaarji     []   
4068  371085                                          Sharkskin     []   
4105   48382    The Book of Mormon Movie, Volume 1: The Journey     []   
4118  325140                             Hum To Mohabbat Karega     []   
4293  357834                                       The Algerian     []   
4314  137955                                          Crowsnest     []   
4385  206412                              Lisa Picard Is Famous     []   
4400  219716                                           Sparkler     []   
4413  335874                                          Childless     []   
4458  279759                                Harrison Montgomery     []   
4504  331493                            Light from the Darkroom     []   
4550  294550                       The Outrageous Sophie Tucker     []   
4553  380097                         America Is Still the Place     []   
4562  297100                           The Little Ponderosa Zoo     []   
4566  325579                                       Diamond Ruff     []   
4569  198370                                     Mutual Friends     []   
4571  328307  Rise of the Entrepreneur: The Search for a Bet...     []   
4581  281189                               Gory Gory Hallelujah     []   
4611  162396                                       The Big Swap     []   
4622  365052                                  The Looking Glass     []   
4633  300327                                        Death Calls     []   
4657  320435                                          UnDivided     []   
4674  194588                   Short Cut to Nirvana: Kumbh Mela     []   
4681  176074                                       Reality Show     []   
4714  282128                           An American in Hollywood     []   
4716   38786  The Blood of My Brother: A Story of Death in Iraq     []   
4801  126186                                   Shanghai Calling     []   

      vote_average  vote_count  popularity  \
3971           6.0           1    0.214704   
3992           9.5           2    0.296981   
4068           0.0           0    0.027801   
4105           5.0           2    0.031947   
4118           0.0           0    0.001186   
4293           0.0           0    0.025364   
4314           4.8          12    0.057564   
4385           4.0           1    0.690089   
4400           0.0           1    0.547654   
4413           4.5           2    0.243853   
4458           0.0           0    0.006943   
4504           0.0           0    0.012942   
4550           0.0           0    0.021419   
4553           0.0           0    0.000000   
4562           2.0           1    0.073079   
4566           2.4           4    0.165257   
4569           0.0           0    0.136721   
4571           8.0           1    0.052942   
4581           1.0           1    0.033883   
4611           0.0           0    0.627763   
4622           7.0           1    0.062979   
4633           0.0           0    0.005883   
4657           0.0           0    0.010607   
4674           0.0           0    0.004998   
4681           5.5           2    0.472123   
4714           0.0           0    0.015697   
4716           0.0           0    0.005256   
4801           5.7           7    0.857008   

                                               keywords  \
3971                                                 []   
3992                                                 []   
4068                                                 []   
4105                                                 []   
4118                                                 []   
4293                                                 []   
4314                                                 []   
4385                                                 [] 

## -> 데이터 전처리 끝

In [36]:
movies_df

id                                     title  \
0      19995                                    Avatar   
1        285  Pirates of the Caribbean: At World's End   
2     206647                                   Spectre   
3      49026                     The Dark Knight Rises   
4      49529                               John Carter   
...      ...                                       ...   
4798    9367                               El Mariachi   
4799   72766                                 Newlyweds   
4800  231617                 Signed, Sealed, Delivered   
4801  126186                          Shanghai Calling   
4802   25975                         My Date with Drew   

                                             genres  vote_average  vote_count  \
0     [Action, Adventure, Fantasy, Science Fiction]           7.2       11800   
1                      [Adventure, Fantasy, Action]           6.9        4500   
2                        [Action, Adventure, Crime]           6.3        4466   
3                  [Action, Crime, Drama, Thriller]           7.6        9106   
4              [Action, Adventure, Science Fiction]           6.1        2124   
...                                             ...           ...         ...   
4798                      [Action, Crime, Thriller]           6.6         238   
4799                              [Comedy, Romance]           5.9           5   
4800             [Comedy, Drama, Romance, TV Movie]           7.0           6   
4801                                             []           5.7           7   
4802                                  [Documentary]           6.3          16   

      popularity                                           keywords  \
0     150.437577  [culture clash, future, space war, space colon...   
1     139.082615  [ocean, drug abuse, exotic island, east india ...   
2     107.376788  [spy, based on novel, secret agent, sequel, mi...   
3     112.312950  [dc comics, crime fighter, terrorist, secret i...   
4      43.926995  [based on novel, mars, medallion, space travel...   
...          ...                                                ...   
4798   14.269792  [united states–mexico barrier, legs, arms, pap...   
4799    0.642552                                                 []   
4800    1.444476  [date, love at first sight, narration, investi...   
4801    0.857008                                                 []   
4802    1.929883          [obsession, camcorder, crush, dream girl]   

                                               overview  
0     In the 22nd century, a paraplegic Marine is di...  
1     Captain Barbossa, long believed to be dead, ha...  
2     A cryptic message from Bond’s past sends him o...  
3     Following the death of District Attorney Harve...  
4     John Carter is a war-weary, former military ca...  
...                                                 ...  
4798  El Mariachi just wants to play his guitar and ...  
4799  A newlywed couple's honeymoon is upended by th...  
4800  "Signed, Sealed, Delivered" introduces a dedic...  
4801  When ambitious New York attorney Sam is sent t...  
4802  Ever since the second grade when he first saw ...  

[4803 rows x 8 columns]

## 장르 컨텐츠 유사도 측정

In [98]:
from sklearn.feature_extraction.text import CountVectorizer

In [37]:
# 참고 : CountVectorizer에 대하여
# CountVectorizer는 다음 세가지를 수행한다.
# 1. 문서를 토큰 리스트로 변환한다.
# 2. 각 문서에서 토큰의 출현 빈도를 센다.
# 3. 각 문서를 BOW(Bag of Words) 인코딩 벡터로 변환한다.

from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?',
    'The last document?',
]

# 토큰 별 인덱스 사전을 만들어준다.
vect = CountVectorizer()
vect.fit(corpus)

vect.vocabulary_

{'this': 9,
 'is': 3,
 'the': 7,
 'first': 2,
 'document': 1,
 'second': 6,
 'and': 0,
 'third': 8,
 'one': 5,
 'last': 4}

In [38]:
movies_df['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...                      
4798                        [Action, Crime, Thriller]
4799                                [Comedy, Romance]
4800               [Comedy, Drama, Romance, TV Movie]
4801                                               []
4802                                    [Documentary]
Name: genres, Length: 4803, dtype: object

In [40]:
# CountVectorizer를 적용하기 위해 공백문자로 word 단위가 구분되는 문자열로 변환. 
movies_df['genres_literal'] = movies_df['genres'].apply(lambda x : (' ').join(x))
movies_df['genres_literal']

0       Action Adventure Fantasy Science Fiction
1                       Adventure Fantasy Action
2                         Action Adventure Crime
3                    Action Crime Drama Thriller
4               Action Adventure Science Fiction
                          ...                   
4798                       Action Crime Thriller
4799                              Comedy Romance
4800               Comedy Drama Romance TV Movie
4801                                            
4802                                 Documentary
Name: genres_literal, Length: 4803, dtype: object

In [41]:
movies_df['genres_literal'][0]

'Action Adventure Fantasy Science Fiction'

In [46]:
# CountVectorizer로 학습시켰더니 4803개 영화에 대한 276개 장르의 '장르 매트릭스'가 생성되었다.

count_vect = CountVectorizer(min_df=0, ngram_range=(1, 2))  # min_df: 단어장에 들어갈 최소빈도, ngram_range: 1 <= n <= 2
genre_mat = count_vect.fit_transform(movies_df['genres_literal'])

print(genre_mat.shape)
print(genre_mat)
# 영화 별 장르 인덱스 사전을 만들어준다

(4803, 276)
  (0, 0)	1
  (0, 16)	1
  (0, 124)	1
  (0, 232)	1
  (0, 138)	1
  (0, 1)	1
  (0, 24)	1
  (0, 135)	1
  (0, 233)	1
  (1, 0)	1
  (1, 16)	1
  (1, 124)	1
  (1, 24)	1
  (1, 125)	1
  (2, 0)	1
  (2, 16)	1
  (2, 1)	1
  (2, 64)	1
  (2, 20)	1
  (3, 0)	1
  (3, 64)	1
  (3, 90)	1
  (3, 234)	1
  (3, 4)	1
  (3, 68)	1
  :	:
  (4796, 90)	1
  (4796, 234)	1
  (4796, 106)	1
  (4796, 144)	1
  (4797, 234)	1
  (4797, 153)	1
  (4797, 157)	1
  (4798, 0)	1
  (4798, 64)	1
  (4798, 234)	1
  (4798, 4)	1
  (4798, 78)	1
  (4799, 44)	1
  (4799, 214)	1
  (4799, 58)	1
  (4800, 90)	1
  (4800, 44)	1
  (4800, 214)	1
  (4800, 104)	1
  (4800, 50)	1
  (4800, 250)	1
  (4800, 182)	1
  (4800, 251)	1
  (4800, 229)	1
  (4802, 80)	1


In [47]:
# CountVectorizer로 학습시켰더니 4803개 영화에 대한 22개 장르의 '장르 매트릭스'가 생성되었다.
count_vect2 = CountVectorizer(min_df=1, ngram_range=(1, 1))  # min_df: 단어장에 들어갈 최소빈도, ngram_range: 1 <= n <= 2
genre_mat2 = count_vect2.fit_transform(movies_df['genres_literal'])
print(genre_mat2.shape)
print(genre_mat2)

(4803, 22)
  (0, 0)	1
  (0, 1)	1
  (0, 8)	1
  (0, 17)	1
  (0, 9)	1
  (1, 0)	1
  (1, 1)	1
  (1, 8)	1
  (2, 0)	1
  (2, 1)	1
  (2, 4)	1
  (3, 0)	1
  (3, 4)	1
  (3, 6)	1
  (3, 18)	1
  (4, 0)	1
  (4, 1)	1
  (4, 17)	1
  (4, 9)	1
  (5, 0)	1
  (5, 1)	1
  (5, 8)	1
  (6, 2)	1
  (6, 7)	1
  (7, 0)	1
  :	:
  (4792, 18)	1
  (4792, 12)	1
  (4792, 15)	1
  (4793, 6)	1
  (4794, 18)	1
  (4794, 3)	1
  (4794, 12)	1
  (4795, 6)	1
  (4796, 17)	1
  (4796, 9)	1
  (4796, 6)	1
  (4796, 18)	1
  (4797, 18)	1
  (4797, 10)	1
  (4798, 0)	1
  (4798, 4)	1
  (4798, 18)	1
  (4799, 3)	1
  (4799, 16)	1
  (4800, 6)	1
  (4800, 3)	1
  (4800, 16)	1
  (4800, 19)	1
  (4800, 13)	1
  (4802, 5)	1


### 코사인 유사도(cosine_similarity)이용해서 영화별 유사도 계산

In [48]:
# 코사인 유사도에 의해 4803개 영화 각각 유사한 영화들이 계산됨
from sklearn.metrics.pairwise import cosine_similarity
genre_sim = cosine_similarity(genre_mat, genre_mat)

print(genre_sim.shape)
print(genre_sim[:10])

(4803, 4803)
[[1.         0.59628479 0.4472136  ... 0.         0.         0.        ]
 [0.59628479 1.         0.4        ... 0.         0.         0.        ]
 [0.4472136  0.4        1.         ... 0.         0.         0.        ]
 ...
 [0.75592895 0.3380617  0.50709255 ... 0.         0.         0.        ]
 [0.4472136  0.6        0.2        ... 0.         0.         0.        ]
 [0.74535599 0.8        0.6        ... 0.         0.         0.        ]]


In [56]:
print(genre_sim[0][:5])
print(genre_sim[1][:5])
print(genre_sim[2][:5])
print(genre_sim[3][:5])
print(genre_sim[4][:5])

[1.         0.59628479 0.4472136  0.12598816 0.75592895]
[0.59628479 1.         0.4        0.16903085 0.3380617 ]
[0.4472136  0.4        1.         0.3380617  0.50709255]
[0.12598816 0.16903085 0.3380617  1.         0.14285714]
[0.75592895 0.3380617  0.50709255 0.14285714 1.        ]


In [49]:
# 자료를 정렬하는 것이 아니라 순서만 알고 싶다면 argsort
# 유사도가 높은 영화를 앞에서부터 순서대로 보여줌

# 0번째 영화의 경우 유사도 순서 : 0번, 3494번, 813번, ..., 2401 순서
genre_sim_sorted_ind = genre_sim.argsort()[:, ::-1] # ::-1 : 역순으로 정렬
print(genre_sim_sorted_ind[:5])

[[   0 3494  813 ... 3038 3037 2401]
 [ 262    1  129 ... 3069 3067 2401]
 [   2 1740 1542 ... 3000 2999 2401]
 [2195 1850 3316 ...  887 2544 4802]
 [ 102 2995   56 ... 3046 3045 2401]]


In [50]:
genre_sim_sorted_ind

array([[   0, 3494,  813, ..., 3038, 3037, 2401],
       [ 262,    1,  129, ..., 3069, 3067, 2401],
       [   2, 1740, 1542, ..., 3000, 2999, 2401],
       ...,
       [4800, 3809, 1895, ..., 2229, 2230,    0],
       [4802, 1594, 1596, ..., 3204, 3205,    0],
       [4802, 4710, 4521, ..., 3140, 3141,    0]])

## 추천 ver1. 장르 코사인 유사도에 의해 영화를 추천하는 함수

### 함수 분석

In [57]:
# 인자로 입력된 movies_df DataFrame에서 'title' 컬럼이 입력된 title_name 값인 DataFrame추출
title_movie = movies_df[movies_df['title'] == 'Avatar']
title_movie

id   title                                         genres  vote_average  \
0  19995  Avatar  [Action, Adventure, Fantasy, Science Fiction]           7.2   

   vote_count  popularity                                           keywords  \
0       11800  150.437577  [culture clash, future, space war, space colon...   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   

                             genres_literal  
0  Action Adventure Fantasy Science Fiction

In [59]:
# title_named을 가진 DataFrame의 index 객체를 ndarray로 반환하고 
# sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n 개의 index 추출
title_index = title_movie.index.values
title_index

array([0])

In [60]:
similar_indexes = genre_sim_sorted_ind[title_index, :10]
similar_indexes

array([[   0, 3494,  813,  870,   46,   14, 1296, 1652,  419,  420]])

In [61]:
# 추출된 top_n index들 출력. top_n index는 2차원 데이터 임.
# dataframe에서 index로 사용하기 위해서 2차원 array를 1차원 array로 변경
similar_indexes = similar_indexes.reshape(-1)
print(similar_indexes)

[   0 3494  813  870   46   14 1296 1652  419  420]


In [121]:
movies_df.iloc[similar_indexes]

id                                      title  \
0      19995                                     Avatar   
3494   27549  Beastmaster 2: Through the Portal of Time   
813     1924                                   Superman   
870     8536                                Superman II   
46    127585                 X-Men: Days of Future Past   
14     49521                               Man of Steel   
1296    9531                               Superman III   
1652   14164                       Dragonball Evolution   
419     8247                                     Jumper   
420    11253                Hellboy II: The Golden Army   

                                                 genres  vote_average  \
0         [Action, Adventure, Fantasy, Science Fiction]           7.2   
3494      [Action, Adventure, Fantasy, Science Fiction]           4.6   
813       [Action, Adventure, Fantasy, Science Fiction]           6.9   
870       [Action, Adventure, Fantasy, Science Fiction]           6.5   
46        [Action, Adventure, Fantasy, Science Fiction]           7.5   
14        [Action, Adventure, Fantasy, Science Fiction]           6.5   
1296  [Comedy, Action, Adventure, Fantasy, Science F...           5.3   
1652  [Action, Adventure, Fantasy, Science Fiction, ...           2.9   
419               [Adventure, Fantasy, Science Fiction]           5.9   
420               [Adventure, Fantasy, Science Fiction]           6.5   

      vote_count  popularity  \
0          11800  150.437577   
3494          17    1.478505   
813         1022   48.507081   
870          629   30.515175   
46          6032  118.078691   
14          6359   99.398009   
1296         490   22.164202   
1652         462   21.677732   
419         1799   21.218000   
420         1527   58.579760   

                                               keywords  \
0     [culture clash, future, space war, space colon...   
3494  [based on novel, time travel, sequel, psychotr...   
813   [saving the world, journalist, dc comics, crim...   
870   [saving the world, dc comics, sequel, superher...   
46    [1970s, mutant, time travel, marvel comic, bas...   
14    [saving the world, dc comics, superhero, based...   
1296  [saving the world, dc comics, super computer, ...   
1652  [karate, superhero, revenge, dragon, duringcre...   
419   [adolescence, based on novel, loss of child, f...   
420   [auction, northern ireland, resignation, super...   

                                               overview  \
0     In the 22nd century, a paraplegic Marine is di...   
3494  Mark Singer returns as Dar, the warrior who ca...   
813   Mild-mannered Clark Kent works as a reporter a...   
870   Three escaped criminals from the planet Krypto...   
46    The ultimate X-Men ensemble fights a war for t...   
14    A young boy learns that he has extraordinary p...   
1296  Aiming to defeat the Man of Steel, wealthy exe...   
1652  The young warrior Son Goku sets out on a quest...   
419   David Rice is a man who knows no boundaries, a...   
420   In this continuation to the adventure of the d...   

                                         genres_literal  
0              Action Adventure Fantasy Science Fiction  
3494           Action Adventure Fantasy Science Fiction  
813            Action Adventure Fantasy Science Fiction  
870            Action Adventure Fantasy Science Fiction  
46             Action Adventure Fantasy Science Fiction  
14             Action Adventure Fantasy Science Fiction  
1296    Comedy Action Adventure Fantasy Science Fiction  
1652  Action Adventure Fantasy Science Fiction Thriller  
419                   Adventure Fantasy Science Fiction  
420                   Adventure Fantasy Science Fiction

### 실제 함수

In [63]:
def find_sim_movie_ver1(df, sorted_ind, title_name, top_n=10):
    
    # 인자로 입력된 movies_df DataFrame에서 'title' 컬럼이 입력된 title_name 값인 DataFrame추출
    title_movie = df[df['title'] == title_name]
    
    # title_named을 가진 DataFrame의 index 객체를 ndarray로 반환하고 
    # sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n 개의 index 추출
    title_index = title_movie.index.values
    similar_indexes = sorted_ind[title_index, :(top_n)]
    
    # 추출된 top_n index들 출력. top_n index는 2차원 데이터 임.
    # dataframe에서 index로 사용하기 위해서 1차원 array로 변경
    print(similar_indexes)    
    # 2차원 데이터를 1차원으로 변환
    similar_indexes = similar_indexes.reshape(-1)
    
    return df.iloc[similar_indexes]

### 영화 Gotfather와 장르가 유사한 영화 10개 추천

In [69]:
similar_movies = find_sim_movie_ver1(movies_df, genre_sim_sorted_ind, 'The Godfather', 10)

similar_movies[['title', 'vote_average', 'genres', 'vote_count']]
# 문제 ; 평점 기반으로 추천하고자 하는데, vote_count가 낮은 영화는 제외하고 싶음

[[2731 1243 3636 1946 2640 4065 1847 4217  883 3866]]


title  vote_average  \
2731                          The Godfather: Part II           8.3   
1243                                    Mean Streets           7.2   
3636                                   Light Sleeper           5.7   
1946  The Bad Lieutenant: Port of Call - New Orleans           6.0   
2640         Things to Do in Denver When You're Dead           6.7   
4065                                      Mi America           0.0   
1847                                      GoodFellas           8.2   
4217                                            Kids           6.8   
883                              Catch Me If You Can           7.7   
3866                                     City of God           8.1   

              genres  vote_count  
2731  [Drama, Crime]        3338  
1243  [Drama, Crime]         345  
3636  [Drama, Crime]          15  
1946  [Drama, Crime]         326  
2640  [Drama, Crime]          85  
4065  [Drama, Crime]           0  
1847  [Drama, Crime]        3128  
4217  [Drama, Crime]         279  
883   [Drama, Crime]        3795  
3866  [Drama, Crime]        1814

In [70]:
# 평점 기준으로 정렬(sort_values)해보니 평가횟수(vote_count)가 낮은 것들도 포함됨. 평가횟수 반영한 평점(가중평점)이 필요함
movies_df[['title','vote_average','vote_count']].sort_values('vote_average', ascending=False)[:10]

title  vote_average  vote_count
3519          Stiff Upper Lips          10.0           1
4247     Me You and Five Bucks          10.0           2
4045     Dancer, Texas Pop. 81          10.0           1
4662            Little Big Top          10.0           1
3992                 Sardaarji           9.5           2
2386            One Man's Hero           9.3           2
2970        There Goes My Baby           8.5           2
1881  The Shawshank Redemption           8.5        8205
2796     The Prisoner of Zenda           8.4          11
3337             The Godfather           8.4        5893

## 가중평점(평점&평가횟수) 반영한 영화 추천

In [71]:
# 상위 60%에 해당하는 vote_count를 최소 투표 횟수인 m으로 지정
C = movies_df['vote_average'].mean()
m = movies_df['vote_count'].quantile(0.6)

In [72]:
# C: 전체 영화에 대한 평균평점 = 약 6점
# m: 평점을 부여하기 위한 최소 투표 횟수 = 370회(상위 60% 수준)
print('C:',round(C,3), 'm:',round(m,3))

C: 6.092 m: 370.2


### 가중평점을 계산하는 함수

In [73]:
def weighted_vote_average(record):
    v = record['vote_count']
    R = record['vote_average']
    
    return ( (v/(v+m)) * R ) + ( (m/(m+v)) * C )

In [74]:
# 기존 데이터에 가중평점 칼럼 추가
movies_df['weighted_vote'] = movies_df.apply(weighted_vote_average, axis=1)

In [75]:
movies_df

id                                     title  \
0      19995                                    Avatar   
1        285  Pirates of the Caribbean: At World's End   
2     206647                                   Spectre   
3      49026                     The Dark Knight Rises   
4      49529                               John Carter   
...      ...                                       ...   
4798    9367                               El Mariachi   
4799   72766                                 Newlyweds   
4800  231617                 Signed, Sealed, Delivered   
4801  126186                          Shanghai Calling   
4802   25975                         My Date with Drew   

                                             genres  vote_average  vote_count  \
0     [Action, Adventure, Fantasy, Science Fiction]           7.2       11800   
1                      [Adventure, Fantasy, Action]           6.9        4500   
2                        [Action, Adventure, Crime]           6.3        4466   
3                  [Action, Crime, Drama, Thriller]           7.6        9106   
4              [Action, Adventure, Science Fiction]           6.1        2124   
...                                             ...           ...         ...   
4798                      [Action, Crime, Thriller]           6.6         238   
4799                              [Comedy, Romance]           5.9           5   
4800             [Comedy, Drama, Romance, TV Movie]           7.0           6   
4801                                             []           5.7           7   
4802                                  [Documentary]           6.3          16   

      popularity                                           keywords  \
0     150.437577  [culture clash, future, space war, space colon...   
1     139.082615  [ocean, drug abuse, exotic island, east india ...   
2     107.376788  [spy, based on novel, secret agent, sequel, mi...   
3     112.312950  [dc comics, crime fighter, terrorist, secret i...   
4      43.926995  [based on novel, mars, medallion, space travel...   
...          ...                                                ...   
4798   14.269792  [united states–mexico barrier, legs, arms, pap...   
4799    0.642552                                                 []   
4800    1.444476  [date, love at first sight, narration, investi...   
4801    0.857008                                                 []   
4802    1.929883          [obsession, camcorder, crush, dream girl]   

                                               overview  \
0     In the 22nd century, a paraplegic Marine is di...   
1     Captain Barbossa, long believed to be dead, ha...   
2     A cryptic message from Bond’s past sends him o...   
3     Following the death of District Attorney Harve...   
4     John Carter is a war-weary, former military ca...   
...                                                 ...   
4798  El Mariachi just wants to play his guitar and ...   
4799  A newlywed couple's honeymoon is upended by th...   
4800  "Signed, Sealed, Delivered" introduces a dedic...   
4801  When ambitious New York attorney Sam is sent t...   
4802  Ever since the second grade when he first saw ...   

                                genres_literal  weighted_vote  
0     Action Adventure Fantasy Science Fiction       7.166301  
1                     Adventure Fantasy Action       6.838594  
2                       Action Adventure Crime       6.284091  
3                  Action Crime Drama Thriller       7.541095  
4             Action Adventure Science Fiction       6.098838  
...                                        ...            ...  
4798                     Action Crime Thriller       6.290894  
4799                            Comedy Romance       6.089611  
4800             Comedy Drama Romance TV Movie       6.106650  
4801                                                 6.084894  
4802                               Documentary       6.100782  

[4803 row

In [76]:
# 가중평점(weighted_vote) 기준으로 영화 순위 뽑아보기
movies_df[['weighted_vote','title','vote_average','vote_count','genres']].sort_values('weighted_vote', ascending=False)[:10]

weighted_vote                     title  vote_average  vote_count  \
1881       8.396052  The Shawshank Redemption           8.5        8205   
3337       8.263591             The Godfather           8.4        5893   
662        8.216455                Fight Club           8.3        9413   
3232       8.207102              Pulp Fiction           8.3        8428   
65         8.136930           The Dark Knight           8.2       12002   
1818       8.126069          Schindler's List           8.3        4329   
3865       8.123248                  Whiplash           8.3        4254   
809        8.105954              Forrest Gump           8.2        7927   
2294       8.105867             Spirited Away           8.3        3840   
2731       8.079586    The Godfather: Part II           8.3        3338   

                                       genres  
1881                           [Drama, Crime]  
3337                           [Drama, Crime]  
662                                   [Drama]  
3232                        [Thriller, Crime]  
65           [Drama, Action, Crime, Thriller]  
1818                    [Drama, History, War]  
3865                                  [Drama]  
809                  [Comedy, Drama, Romance]  
2294  [Fantasy, Adventure, Animation, Family]  
2731                           [Drama, Crime]

## 추천 ver2. 먼저 장르 유사성 높은 영화 20개 선정 후(F1), 가중평점순 10개 선정(F2)

In [77]:
def find_sim_movie_ver2(df, sorted_ind, title_name, top_n=10):
    title_movie = df[df['title'] == title_name]
    title_index = title_movie.index.values
    
    # top_n의 2배에 해당하는 쟝르 유사성이 높은 index 추출
    similar_indexes = sorted_ind[title_index, :(top_n*2)]
    similar_indexes = similar_indexes.reshape(-1)

    # 기준 영화 index는 제외
    similar_indexes = similar_indexes[similar_indexes != title_index]
    
    # top_n의 2배에 해당하는 후보군에서 weighted_vote 높은 순으로 top_n 만큼 추출
    return df.iloc[similar_indexes].sort_values('weighted_vote', ascending=False)[:top_n]

### 영화 Gotfather에 대해 장르 유사성, 가중평점 반영한 추천 영화 10개를 뽑아보자

In [78]:
movies_df

id                                     title  \
0      19995                                    Avatar   
1        285  Pirates of the Caribbean: At World's End   
2     206647                                   Spectre   
3      49026                     The Dark Knight Rises   
4      49529                               John Carter   
...      ...                                       ...   
4798    9367                               El Mariachi   
4799   72766                                 Newlyweds   
4800  231617                 Signed, Sealed, Delivered   
4801  126186                          Shanghai Calling   
4802   25975                         My Date with Drew   

                                             genres  vote_average  vote_count  \
0     [Action, Adventure, Fantasy, Science Fiction]           7.2       11800   
1                      [Adventure, Fantasy, Action]           6.9        4500   
2                        [Action, Adventure, Crime]           6.3        4466   
3                  [Action, Crime, Drama, Thriller]           7.6        9106   
4              [Action, Adventure, Science Fiction]           6.1        2124   
...                                             ...           ...         ...   
4798                      [Action, Crime, Thriller]           6.6         238   
4799                              [Comedy, Romance]           5.9           5   
4800             [Comedy, Drama, Romance, TV Movie]           7.0           6   
4801                                             []           5.7           7   
4802                                  [Documentary]           6.3          16   

      popularity                                           keywords  \
0     150.437577  [culture clash, future, space war, space colon...   
1     139.082615  [ocean, drug abuse, exotic island, east india ...   
2     107.376788  [spy, based on novel, secret agent, sequel, mi...   
3     112.312950  [dc comics, crime fighter, terrorist, secret i...   
4      43.926995  [based on novel, mars, medallion, space travel...   
...          ...                                                ...   
4798   14.269792  [united states–mexico barrier, legs, arms, pap...   
4799    0.642552                                                 []   
4800    1.444476  [date, love at first sight, narration, investi...   
4801    0.857008                                                 []   
4802    1.929883          [obsession, camcorder, crush, dream girl]   

                                               overview  \
0     In the 22nd century, a paraplegic Marine is di...   
1     Captain Barbossa, long believed to be dead, ha...   
2     A cryptic message from Bond’s past sends him o...   
3     Following the death of District Attorney Harve...   
4     John Carter is a war-weary, former military ca...   
...                                                 ...   
4798  El Mariachi just wants to play his guitar and ...   
4799  A newlywed couple's honeymoon is upended by th...   
4800  "Signed, Sealed, Delivered" introduces a dedic...   
4801  When ambitious New York attorney Sam is sent t...   
4802  Ever since the second grade when he first saw ...   

                                genres_literal  weighted_vote  
0     Action Adventure Fantasy Science Fiction       7.166301  
1                     Adventure Fantasy Action       6.838594  
2                       Action Adventure Crime       6.284091  
3                  Action Crime Drama Thriller       7.541095  
4             Action Adventure Science Fiction       6.098838  
...                                        ...            ...  
4798                     Action Crime Thriller       6.290894  
4799                            Comedy Romance       6.089611  
4800             Comedy Drama Romance TV Movie       6.106650  
4801                                                 6.084894  
4802                               Documentary       6.100782  

[4803 row

In [79]:
genre_sim_sorted_ind

array([[   0, 3494,  813, ..., 3038, 3037, 2401],
       [ 262,    1,  129, ..., 3069, 3067, 2401],
       [   2, 1740, 1542, ..., 3000, 2999, 2401],
       ...,
       [4800, 3809, 1895, ..., 2229, 2230,    0],
       [4802, 1594, 1596, ..., 3204, 3205,    0],
       [4802, 4710, 4521, ..., 3140, 3141,    0]])

In [90]:
similar_movies = find_sim_movie_ver2(movies_df, genre_sim_sorted_ind, 'Superman', 10)
similar_movies[['title', 'vote_average', 'weighted_vote', 'genres', 'vote_count']]

title  vote_average  weighted_vote  \
46                   X-Men: Days of Future Past           7.5       7.418594   
0                                        Avatar           7.2       7.166301   
14                                 Man of Steel           6.5       6.477564   
420                 Hellboy II: The Golden Army           6.5       6.420421   
870                                 Superman II           6.5       6.348901   
232                               The Wolverine           6.3       6.282606   
3208            Star Wars: Clone Wars: Volume 1           8.0       6.221858   
1191                             Small Soldiers           6.2       6.154700   
1932                                     Sheena           5.0       6.030907   
3494  Beastmaster 2: Through the Portal of Time           4.6       6.026658   

                                                 genres  vote_count  
46        [Action, Adventure, Fantasy, Science Fiction]        6032  
0         [Action, Adventure, Fantasy, Science Fiction]       11800  
14        [Action, Adventure, Fantasy, Science Fiction]        6359  
420               [Adventure, Fantasy, Science Fiction]        1527  
870       [Action, Adventure, Fantasy, Science Fiction]         629  
232       [Action, Science Fiction, Adventure, Fantasy]        4053  
3208  [Action, Adventure, Animation, Fantasy, Scienc...          27  
1191  [Comedy, Adventure, Fantasy, Science Fiction, ...         511  
1932  [Action, Adventure, Comedy, Fantasy, Science F...          22  
3494      [Action, Adventure, Fantasy, Science Fiction]          17

## 요약 : Gotfather를 좋아하는 사람에게 영화 추천해주기

### 응용 : Spider-Man 3 좋아하는 사람 기준으로 장르가 유사한 영화를 추천해주자

In [87]:
similar_movies = find_sim_movie_ver2(movies_df, genre_sim_sorted_ind, 'The Amazing Spider-Man',10)
similar_movies[['title', 'vote_average', 'weighted_vote', 'genres', 'vote_count']]

title  vote_average  \
329      The Lord of the Rings: The Return of the King           8.1   
262  The Lord of the Rings: The Fellowship of the Ring           8.0   
199  Pirates of the Caribbean: The Curse of the Bla...           7.5   
19           The Hobbit: The Battle of the Five Armies           7.1   
126                               Thor: The Dark World           6.8   
30                                        Spider-Man 2           6.7   
38                            The Amazing Spider-Man 2           6.5   
107                                           Warcraft           6.3   
208                                   The 13th Warrior           6.4   
836                              The Forbidden Kingdom           6.3   

     weighted_vote                        genres  vote_count  
329       8.011871  [Adventure, Fantasy, Action]        8064  
262       7.922175  [Adventure, Fantasy, Action]        8705  
199       7.429142  [Adventure, Fantasy, Action]        6985  
19        7.027274  [Action, Adventure, Fantasy]        4760  
126       6.748873  [Action, Adventure, Fantasy]        4755  
30        6.652034  [Action, Adventure, Fantasy]        4321  
38        6.466812  [Action, Adventure, Fantasy]        4179  
107       6.270837  [Action, Adventure, Fantasy]        2268  
208       6.270532  [Adventure, Fantasy, Action]         510  
836       6.207437  [Action, Adventure, Fantasy]         461

### 응용 : Enemy at the Gates 좋아하는 사람 기준으로 장르가 유사한 영화를 추천해주자

In [88]:
similar_movies = find_sim_movie_ver2(movies_df, genre_sim_sorted_ind, 'Enemy at the Gates',10)
similar_movies[['title', 'vote_average', 'weighted_vote', 'genres', 'vote_count']]

title  vote_average  weighted_vote  \
1525                  Apocalypse Now           8.0       7.708775   
2798  The Boy in the Striped Pyjamas           7.7       7.373173   
2536                 The Deer Hunter           7.8       7.310348   
1662                           Glory           7.4       6.757199   
585                        War Horse           7.0       6.753283   
2662                     Sarah's Key           7.2       6.475666   
2016               The Water Diviner           6.8       6.472943   
557                          Jarhead           6.6       6.434392   
2671      Born on the Fourth of July           6.7       6.405936   
3310                    Far from Men           6.6       6.145019   

            genres  vote_count  
1525  [Drama, War]        2055  
2798  [War, Drama]        1451  
2536  [Drama, War]         921  
1662         [War]         383  
585   [Drama, War]         992  
2662  [Drama, War]         196  
2016  [War, Drama]         431  
557   [Drama, War]         765  
2671  [Drama, War]         395  
3310  [Drama, War]          43